// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmOJhTfjE3mOPbF3gweQSl7bBQazPGQeM',
    appId: '1:363691386147:web:0592fd5cbb19125abb1896',
    messagingSenderId: '363691386147',
    projectId: 'joursafe',
    authDomain: 'joursafe.firebaseapp.com',
    storageBucket: 'joursafe.appspot.com',
    measurementId: 'G-RHQSES9YQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uaynZv_71WOmPmBgyDjG-auDWbrPBGA',
    appId: '1:363691386147:android:b5cb1005b281a756bb1896',
    messagingSenderId: '363691386147',
    projectId: 'joursafe',
    storageBucket: 'joursafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpu-NAyBdZWL4lEtnkeHTUXnOo-A56ArY',
    appId: '1:363691386147:ios:ed35b6ada79a098abb1896',
    messagingSenderId: '363691386147',
    projectId: 'joursafe',
    storageBucket: 'joursafe.appspot.com',
    iosClientId: '363691386147-6ktd6psu5nek80cf9fpu5n1ialdgqqe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.joursafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpu-NAyBdZWL4lEtnkeHTUXnOo-A56ArY',
    appId: '1:363691386147:ios:1c2011b5a2a0850cbb1896',
    messagingSenderId: '363691386147',
    projectId: 'joursafe',
    storageBucket: 'joursafe.appspot.com',
    iosClientId: '363691386147-9ldmvdv7qjnkga0u9auibvqfh3khufb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.joursafe.RunnerTests',
  );
}
